<a href="https://colab.research.google.com/github/kathirvelgithub/Machine_learning/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Logistic Regression


In [ ]:
# Program to check the right Age to voting (Binary LogisticRegression)

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

x =np.array([[10],[13],[17],[18],[21],[22],[25],[28]])
y =np.array([0,0,0,1,1,1,1,1])

model = LogisticRegression(max_iter=1000)

model.fit(x,y)

y2 =model.predict([[24]])

y3 =model.predict_proba([[24]])

print("Prediction",y2)
print("probality",y3)

Prediction [1]
probality [[0.00434756 0.99565244]]


In [ ]:
# To classify the type of iris flower (multi Class Logisticregression)

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris

df =pd.read_csv("/content/IRIS.csv")
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
# method 1
model = LogisticRegression(max_iter=1000)

x =df.drop(columns="species")
y =df["species"]


model.fit(x,y)

#pre =df.head(1).drop(columns="species")

dt =pd.DataFrame({"sepal_length":[6.8] , "sepal_width":[4.2] ,"petal_length":[5.3] ,"petal_width":[2.6]})

y2 =model.predict(dt)
y3 =model.predict_proba(dt)

print("Prediction",y2)
print("Probality",y3)

['Iris-virginica']


In [ ]:
# method 2

model = LogisticRegression(max_iter=1000)

x =df.drop(columns="species")
y =df["species"]

x_train,x_test, y_train,y_test = train_test_split(x,y)

model.fit(x_train,y_train)

y2 =model.predict(x_test)
y3 =model.predict_proba(x_test)
y4 =accuracy_score(y_test,y2)

print("Prediction",y2)
print("Probality",y3)
print("Accuracy",y4)

Prediction ['Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa']
Probality [[8.69881484e-04 4.89714159e-01 5.09415960e-01]
 [6.72150306e-03 8.93110780e-01 1.00167717e-01]
 [9.37172527e-01 6.28267539e-02 7.18953257e-07]
 [9.20258063e-06 2.70344861e-02 9.72956311e-01]
 [9.76787071e-01 2.32128549e-02 7.40741291e-08]
 [9.78843531e-01 2.11564364e-02 3.30684489e-08]
 [1.70645165e-06 2.50884047e-02 9.74909889e-01]
 [2.01019269e-02 9.

In [ ]:
# method 3 (Regularization)

model = LogisticRegression(C=0.2)

x =df.drop(columns="species")
y =df["species"]

x_train,x_test, y_train,y_test = train_test_split(x,y)

model.fit(x_train,y_train)

y2 =model.predict(x_test)
y3 =model.predict_proba(x_test)
y4 =accuracy_score(y_test,y2)

print("Prediction",y2)

Prediction ['Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor']


In [ ]:
# Titanic Survival Prediction: Use logistic regression to predict survival

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression ,LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris

df =pd.read_csv("/content/titanic_dataset.csv")
df.head(100)

PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
..          ...       ...     ...   
95           96         0       3   
96           97         0       1   
97           98         1       1   
98           99         1       2   
99          100         0       2   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
..                                                ...     ...   ...    ...   
95                        Shorney, Mr. Charles Joseph    male   NaN      0   
96                          Goldschmidt, Mr. George B    male  71.0      0   
97                    Greenfield, Mr. William Bertram    male  23.0      0   
98               Doling, Mrs. John T (Ada Julia Bone)  female  34.0      0   
99                                  Kantor, Mr. Sinai    male  34.0      1   

    Parch            Ticket     Fare    Cabin Embarked  
0       0         A/5 21171   7.2500      NaN        S  
1       0          PC 17599  71.2833      C85        C  
2       0  STON/O2. 3101282   7.9250      NaN        S  
3       0            113803  53.1000     C123        S  
4       0            373450   8.0500      NaN        S  
..    ...               ...      ...      ...      ...  
95      0            374910   8.0500      NaN        S  
96      0          PC 17754  34.6542       A5        C  
97      1          PC 17759  63.3583  D10 D12        C  
98      1            231919  23.0000      NaN        S  
99      0            244367  26.0000      NaN        S  

[100 rows x 12 columns]

In [ ]:
model = LogisticRegression()

x =pd.DataFrame(df.PassengerId )
x.dropna()
y =df["Survived"]

x_train,x_test, y_train,y_test = train_test_split(x,y)

model.fit(x_train,y_train)

y2 =model.predict(x_test)
#y3 =model.predict_proba(x_test)
#y4 =accuracy_score(y_test,y2)

print("Prediction",y2)
print("Probality",y3)
print("Accuracy",y4)


Prediction [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0]
Probality [[0.65172765 0.34827235]
 [0.6443268  0.3556732 ]
 [0.65114289 0.34885711]
 [0.65152303 0.34847697]
 [0.65125988 0.34874012]
 [0.64636027 0.35363973]
 [0.64379547 0.35620453]
 [0.64258389 0.35741611]
 [0.64326378 0.35673622]
 [0.64562411 0.35437589]
 [0.64979622 0.35020378]
 [0.64947384 0.35052616]
 [0.64762483 0.35237517]
 [0.65090886 0.34909114]
 [0.65292497 0.34707503]
 [0.65307085 0.34692915]
 [0.64367734 0.35632266]
 [0.64856457 0.35143543]
 [0.64524104 0.35475896]
 [0.65237035 0.34762965]
 [0.65263312 0.34736688]


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import nltk
from nltk.corpus import stopwords
import string

# Download stopwords
nltk.download('stopwords')

# Load the dataset
url = "https://raw.githubusercontent.com/venky0112/Venkatesh_Tomar-Spam-Email-Detection-Model/main/mail_data.csv"
df = pd.read_csv(url)

# Display basic information
print(df.info())
print(df.head())

# Data preprocessing
# Convert labels to binary values: 'spam' -> 1, 'ham' -> 0
df['Category'] = df['Category'].map({'spam': 1, 'ham': 0})

# Function to clean text
def clean_text(text):
    text = text.lower()  # Lowercase text
    text = ''.join([char for char in text if char not in string.punctuation])  # Remove punctuation
    words = text.split()
    words = [word for word in words if word not in stopwords.words('english')]  # Remove stopwords
    return ' '.join(words)

# Apply text cleaning
df['cleaned_text'] = df['Message'].apply(clean_text)

# Feature extraction using TF-IDF Vectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['cleaned_text'])
y = df['Category']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the logistic regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")
print("Classification Report:")
print(classification_report(y_test, y_pred))


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB
None
  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
Accuracy: 0.96
Classification Report:
              precision    recall  f1-score   support

           0       0.95      1.00      0.97       966
           1       0.97      0.68      0.80       149

    accuracy                           0.96      1115
   macro avg       0.96      0.84      0.89      1115
weighted avg  